# Generated by Django 3.2.15 on 2023-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('phone_verification_code', models.CharField(max_length=10, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('email_verification_code', models.CharField(max_length=10, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('post_address', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
